[package]
name = "katana"
version = "0.1.0"
authors = ["Jason Hooper <nirgle@gmail.com>", "OpenAI Model: GPT-4"]
description = "Simple textual reporting for double-entry accounting ledgers"
edition = "2021"

[dependencies]
regex = "1.7.1"
chrono = "0.4.24"
lazy_static = "1.4.0"
clap = "3.2.23"
